### ISSUE TITLE
PGBoucer `query_wait_timeout` exceeded

### ISSUE THREAD

**Issue by MNThomson** [UVicMartletplace/martletplace#455]
## Describe the bug

Should we increase it beyond the default of 120s? That seems slightly unreasonable: [query_wait_timeout](https://www.pgbouncer.org/config.html)
```log
martletplace_datalayer      | 2024-07-21 19:29:29.312 UTC [9] WARNING C-0x568e2f1e0430: martletplace/martletplace@172.18.0.15:34676 pooler error: query_wait_timeout
martletplace_user           | error: query_wait_timeout
martletplace_user           |     at Parser.parseErrorMessage (/app/lib/node_modules/pg-protocol/src/parser.ts:369:69)
martletplace_user           |     at Parser.handlePacket (/app/lib/node_modules/pg-protocol/src/parser.ts:188:21)
martletplace_user           |     at Parser.parse (/app/lib/node_modules/pg-protocol/src/parser.ts:103:30)
martletplace_user           |     at Socket.<anonymous> (/app/lib/node_modules/pg-protocol/src/index.ts:7:48)
martletplace_user           |     at Socket.emit (node:events:519:28)
martletplace_user           |     at Socket.emit (node:domain:488:12)
martletplace_user           |     at addChunk (node:internal/streams/readable:559:12)
martletplace_user           |     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
martletplace_user           |     at Socket.Readable.push (node:internal/streams/readable:390:5)
martletplace_user           |     at TCP.onStreamRead (node:internal/stream_base_commons:191:23) {
martletplace_user           |   length: 39,
martletplace_user           |   severity: 'FATAL',
martletplace_user           |   code: '08P01',
martletplace_user           |   detail: undefined,
martletplace_user           |   hint: undefined,
martletplace_user           |   position: undefined,
martletplace_user           |   internalPosition: undefined,
martletplace_user           |   internalQuery: undefined,
martletplace_user           |   where: undefined,
martletplace_user           |   schema: undefined,
martletplace_user           |   table: undefined,
martletplace_user           |   column: undefined,
martletplace_user           |   dataType: undefined,
martletplace_user           |   constraint: undefined,
martletplace_user           |   file: undefined,
martletplace_user           |   line: undefined,
martletplace_user           |   routine: undefined,
martletplace_user           |   query: "\n        SELECT * FROM users WHERE user_id = '1'\n      ",
martletplace_user           |   params: undefined
martletplace_user           | }
```

**Comment by kylestang** [comment]
If our queries are waiting 120s there's other problems. What was the context for this? Load test or normal use?

**Comment by MNThomson** [comment]
Loadtest. Getting this error a lot.

Needs some investigation as to why queries are taking this long
